language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:starts -DgCache=$HOME/.cache; ls $HOME/build/marwanmaalouf/build $HOME/build/marwanmaalouf/cache $HOME/build/marwanmaalouf/store;

cache:
    directories:
    - $HOME/.m2
    - $HOME/.cache
