language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:starts -DgCache=$HOME/.cache 
    - ls -a 
    
cache:
    directories:
    - $HOME/.m2
    - $HOME/.starts
