language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:starts 
    - ls -a .starts
    
cache:
    directories:
    - $HOME/.m2
    - $HOME/starts_cache
