language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - ls -R $HOME/build/marwanmaalouf/
    - mvn starts:starts -DgCache=$HOME/.cache 
    - ls -R $HOME/build/marwanmaalouf/

cache:
    directories:
    - $HOME/.m2
    - $HOME/.cache
