language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - cp -r $HOME/.cache/jdeps-cache ./; mvn starts:starts; cp -r ./jdeps-cache $HOME/.cache/

cache:
    directories:
    - $HOME/.m2
    - $HOME/.cache
