language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:starts 
    - pwd
    
cache:
    directories:
    - $HOME/.m2
    - $HOME/build/marwanmaalouf/starts/.starts
