language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:starts -DstartsLogging=FINEST
    
cache:
    directories:
    - $HOME/.m2
    - .starts
    - starts-core/.starts
    - starts-plugin/.starts
