language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:starts 
    - ls -a /home/travis/build/marwanmaalouf/starts/.starts
    
cache:
    directories:
    - $HOME/.m2
    - $HOME/build/marwanmaalouf/starts/.starts
