language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - mvn starts:run; mvn starts:starts
    - ls -Ra
cache:
    directories:
    - $HOME/.m2
    - .starts
