language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8

script:
    - cp -y $HOME/starts_cache/.starts ./
    - mvn starts:starts 
    - ls -a .starts
    - cp -y .starts $HOME/starts_cache/
    
cache:
    directories:
    - $HOME/.m2
    - $HOME/starts_cache
